### PR TITLE
[go_router] Fix chained top-level redirects not being fully resolved

### LINKED ISSUE #178984: [go_router] Chained/Recursive redirection stops after the first redirect in v16+
### Steps to reproduce

1. Use `go_router` version `^16.0.0` or `^17.0.0`.
2. Define a top-level `redirect` function that handles a chain:
    - If path is `/` -> return `/a`
    - If path is `/a` -> return `/b`
3. Run the app starting at `/`.

### Expected results

In version 15, if a top-level `redirect` returned a new path, the router would immediately evaluate the `redirect` function again against that new path. This allowed for chaining redirects (e.g., `/` -> `/a` -> `/b`).

https://pub.dev/documentation/go_router/latest/topics/Redirection-topic.html

### Actual results

In version 16+, the router stops processing after the first redirect occurs. It navigates to the intermediate route instead of continuing the chain to the final destination.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

void main() {
  runApp(const App());
}

class App extends StatefulWidget {
  const App({super.key});

  @override
  State<App> createState() => _AppState();
}

class _AppState extends State<App> {
  late final GoRouter _router;

  @override
  void initState() {
    _router = GoRouter(
      redirect: (context, state) {
        print('redirect called with location: ${state.matchedLocation}');
        if (state.matchedLocation == '/') {
          print('redirecting to /a');
          return '/a';
        } else if (state.matchedLocation == '/a') {
          print('redirecting to /b');
          return '/b';
        } else {
          print('no redirect');
          return null;
        }
      },
      routes: [
        GoRoute(path: '/', builder: (context, state) => const RScreen()),
        GoRoute(path: '/a', builder: (context, state) => const AScreen()),
        GoRoute(path: '/b', builder: (context, state) => const BScreen()),
      ],
    );
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(routerConfig: _router);
  }
}

class RScreen extends StatelessWidget {
  const RScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return const Center(child: Text('r'));
  }
}

class AScreen extends StatelessWidget {
  const AScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return const Center(child: Text('a'));
  }
}

class BScreen extends StatelessWidget {
  const BScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return const Center(child: Text('b'));
  }
}
```

</details>

### Logs

**Expected Behavior (observed in v15):**
The app should redirect recursively until `null` is returned.
Logs from v15:
```text
I/flutter ( 2159): redirect called with location: /
I/flutter ( 2159): redirecting to /a
I/flutter ( 2159): redirect called with location: /a
I/flutter ( 2159): redirecting to /b
I/flutter ( 2159): redirect called with location: /b
I/flutter ( 2159): no redirect
```
The screen displays "b".

**Actual Behavior (observed in v16 - v17):**
The redirection stops after the first step.
Logs from v16/17:
```text
I/flutter ( 2159): redirect called with location: /
I/flutter ( 2159): redirecting to /a
```
The screen displays "a".

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
sh 2972  (git)-[main]-% flutter doctor -v
[✓] Flutter (Channel stable, 3.38.2, on macOS 26.1 25B78 darwin-arm64, locale en-US) [490ms]
    • Flutter version 3.38.2 on channel stable at /Users/yehorh/opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f5a8537f90 (5 days ago), 2025-11-18 09:27:21 -0500
    • Engine revision b5990e5ccc
    • Dart version 3.10.0
    • DevTools version 2.51.1
    • Feature flags: enable-web, enable-linux-desktop, enable-macos-desktop, enable-windows-desktop, enable-android, enable-ios, cli-animations, enable-native-assets, omit-legacy-version-file,
      enable-lldb-debugging

[✓] Android toolchain - develop for Android devices (Android SDK version 36.0.0) [2.4s]
    • Android SDK at /Users/yehorh/Library/Android/sdk
    • Emulator version 36.2.12.0 (build_id 14214601) (CL:N/A)
    • Platform android-36, build-tools 36.0.0
    • ANDROID_HOME = /Users/yehorh/Library/Android/sdk
    • Java binary at: /Users/yehorh/Library/Java/JavaVirtualMachines/azul-17.0.12/Contents/Home/bin/java
      This JDK is specified in your Flutter configuration.
      To change the current JDK, run: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment Zulu17.52+17-CA (build 17.0.12+7-LTS)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 26.1.1) [1,217ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 17B100
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [13ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Connected device (4 available) [6.4s]
    • Android SDK built for arm64 (mobile) • emulator-5554             • android-arm64  • Android 14 (API 34) (emulator)
    • yiPhone (mobile)                     • 00008101-000E28880AD2001E • ios            • iOS 26.1 23B85
    • macOS (desktop)                      • macos                     • darwin-arm64   • macOS 26.1 25B78 darwin-arm64
    • Chrome (web)                         • chrome                    • web-javascript • Google Chrome 142.0.7444.176
    ! Error: Yehor's Apple Watch 📟 has not finished loading development services. Please select a different device, or wait for the device to load development services and try again. (code 8)

[✓] Network resources [1,081ms]
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by davidmigloz**
Fixes https://github.com/flutter/flutter/issues/178984

The `onEnter` refactor (commit `9ec29b6d23`, PR #8339) split the unified `redirect()` method into `applyTopLegacyRedirect()` (top-level, runs once) and `redirect()` (route-level only). This introduced two regressions:

1. **Top-level redirect chains broken**: `applyTopLegacyRedirect()` returned after one hop — a chain like `/ → /a → /b` stopped at `/a` instead of resolving to `/b`.
2. **Route-level → top-level chains broken**: `processRouteLevelRedirect()` recursed into `redirect()` without re-evaluating the top-level redirect on the new location.

### Fix

Unify top-level and route-level redirects back into `redirect()` as the single entry point for all redirect processing, while keeping the separation of concerns via `applyTopLegacyRedirect()` as an internal helper.

> **Note:** An earlier revision of this PR (v1) kept the split but added recursive calls in both methods. Based on [reviewer feedback](https://github.com/flutter/packages/pull/11108#discussion_r2943354003), the approach was refactored to move `applyTopLegacyRedirect()` inside `redirect()` so the caller (`parseRouteInformationWithDependencies`) doesn't need to know about the two-phase process.

#### Before (broken)

```mermaid
sequenceDiagram
    participant Parser as parseRouteInformationWithDependencies
    participant TopRedir as applyTopLegacyRedirect
    participant Redir as redirect (route-level only)

    Parser->>TopRedir: / (one hop only)
    TopRedir-->>Parser: /a (stops here ✗)
    Parser->>Redir: /a
    Redir->>Redir: route-level redirects
    Note right of Redir: No top-level re-evaluation
    Redir-->>Parser: result
```

#### After (fix)

```mermaid
sequenceDiagram
    participant Parser as parseRouteInformationWithDependencies
    participant Redir as redirect (unified)
    participant TopRedir as applyTopLegacyRedirect

    Parser->>Redir: / (initial matches)
    Redir->>TopRedir: / → top-level redirect chain
    TopRedir->>TopRedir: / → /a → /b (self-recursive)
    TopRedir-->>Redir: /b (fully resolved ✓)
    Redir->>Redir: route-level redirects on /b
    Note right of Redir: If route-level changes location,<br/>recurse → top-level re-evaluated
    Redir-->>Parser: final result
```

#### Key changes

- **`configuration.dart` — `redirect()`**: Now calls `applyTopLegacyRedirect()` first at every cycle, then processes route-level redirects on the post-top-level result. Route-level `_processRouteLevelRedirects` extracted as a helper.
- **`configuration.dart` — `applyTopLegacyRedirect()`**: Self-recursive to fully resolve top-level chains. No functional change from v1.
- **`parser.dart` — `parseRouteInformationWithDependencies()`**: Simplified — no longer calls `applyTopLegacyRedirect` separately. Just passes initial matches to `_navigate()`.
- **`parser.dart` — `_navigate()`**: Removed `preSharedHistory` parameter. Added `context.mounted` guard in the result `.then()` to protect the relocated async boundary.

Both fixes share the existing `redirectHistory` for loop detection and respect `redirectLimit`. The `onEnter` system is completely unaffected — it runs before redirects in the pipeline.

### Tests

- **19 redirect chain tests** (`redirect_chain_test.dart`): top-level chains, async chains, loop detection (including loop-to-initial), route→top cross-type chains, **async cross-type chains** (async top→route, async route→sync top, sync route→async top), **context disposal** during async top-level and route-level redirects, redirect limit boundary (exact limit succeeds, limit+1 fails), shared limit across redirect types.
- **3 onEnter interaction tests** (`on_enter_test.dart`): onEnter called once when chains resolve, onEnter block prevents redirect evaluation.
- **Full suite**: 418 tests pass, 0 regressions.

## Pre-Review Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter].
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I [linked to at least one issue that this PR fixes] in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or I have commented below to indicate which [version change exemption] this PR falls under[^1].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style], or I have commented below to indicate which [CHANGELOG exemption] this PR falls under[^1].
- [x] I updated/added any relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or I have commented below to indicate which [test exemption] this PR falls under[^1].
- [x] All existing and new tests are passing.

[^1]: This PR uses `pending_changelogs/` for versioning and changelog, following the go_router batch release process.

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[the auto-formatter]: https://github.com/flutter/packages/blob/main/script/tool/README.md#format-code
[CLA]: https://cla.developers.google.com/
[linked to at least one issue that this PR fixes]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#overview
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[version change exemption]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#version
[following repository CHANGELOG style]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changelog-style
[CHANGELOG exemption]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changelog
[test exemption]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#tests

### CODE REVIEW

**Comment by chunhtai** [comment]
I remembered this behavior was intentional to preserve previous behavior before onEnter is introduced
cc @omar-hanafy

will take a closer look

**Comment by omar-hanafy** [comment]
Hey @davidmigloz, thanks for the detailed write-up and for putting in the work on this fix.

For context, as @chunhtai mentioned, the single-pass behavior in `applyTopLegacyRedirect()` was intentional during the `onEnter` refactor (#8339). The goal then was to simplify the pipeline: run top-level redirect once, then route-level redirects, with `onEnter` earlier than both. The doc comment explicitly called this out as "at most once".

From the user side though, you are right - this is a regression. Chained top-level redirects worked before v16 and stopped after. Even if the internal change was intentional, this is still a behavior break without a deprecation path.

Your fix looks right to me. I support landing this. Long term, `onEnter` may become the cleaner model, but while `redirect` is still supported, it should keep the behavior users expect.

File: packages/go_router/lib/src/configuration.dart [hunk 1]
```diff
@@ -427,7 +427,20 @@ class RouteConfiguration {
           if (newMatch.isError) {
             return newMatch;
           }
-          return redirect(context, newMatch, redirectHistory: redirectHistory);
+          // Re-evaluate top-level redirect on the new location before
```
Comment (chunhtai) [inline packages/go_router/lib/src/configuration.dart]: since we move the top level redirect to be part of the redirect loop in this method, can we refactor the parseRouteInformationWithDependencies to call this redirect method directly without calling  applyTopLegacyRedirect first?

right now it looks like this
```dart
// In pareser.dart
Future<RouteMatchList> parseRouteInformationWithDependencies(..) {
  configuration.applyTopLegacyRedirect(..);
  configuration.redirect(..);

}

/// in configuration.dart

FutureOr<RouteMatchList> redirect(...) {
   route.redirect(...)
   if (routeChange) {
    applyTopLegacyRedirect(..);
    redirect(..); // recurse
  }
}
```

can it be something like

```dart
// In pareser.dart
Future<RouteMatchList> parseRouteInformationWithDependencies(..) {
  configuration.redirect(..);

}

/// in configuration.dart

FutureOr<RouteMatchList> redirect(...) {
   applyTopLegacyRedirect(..);
   route.redirect(...)
   if (routeChange) {
    redirect(..); // recurse
  }
}
```

**Comment by absar** [comment]
@davidmigloz thank you for fixing the regression. when you have some time could you look into the review, v16+ is breaking redirection for us as well

**Comment by davidmigloz** [comment]
Yes! Sorry, it’s still on my TODO list. I need to find some time to do it.

File: packages/go_router/lib/src/configuration.dart (hunk 1 above)
Comment (davidmigloz) [reply packages/go_router/lib/src/configuration.dart]: Refactored as suggested. `redirect()` is now the single entry point: it calls `applyTopLegacyRedirect()` first (still self-recursive for top-level chains), then runs route-level redirects on the post-top-level result, and recurses if a route-level redirect changes the location. `parseRouteInformationWithDependencies` no longer calls `applyTopLegacyRedirect` directly, and the `preSharedHistory` plumbing in `_navigate` has been removed. Also added a `context.mounted` guard in `_navigate`'s result handler to cover the async boundary that moved from the parser into `redirect()`, plus new tests for async cross-type redirect chains and context disposal during async redirects.

**Comment by davidmigloz** [comment]
@chunhtai feedback addressed!

**Review by chunhtai — APPROVED** [review]
LGTM

**Review by hannah-hyj — APPROVED** [review]
LGTM

**Comment by hannah-hyj** [comment]
CI is failing, you need to run `dart format` on packages/go_router/lib/src/configuration.dart

**Comment by davidmigloz** [comment]
fixed!
